#include <stdio.h>
#include <util/vector.h>

extern inline void vectorN_copy( void* dest, const void* old, int count, size_t size);
extern inline void vector3i_set(int v[3], int a, int b, int c);
extern inline void vector4i_set(int v[3], int a, int b, int c, int w);
extern inline void vector3i_copy(int dest[3], const int src[3]);
extern inline void vector4i_copy(int dest[4], const int src[4]);
extern inline int vectorNi_dot(const int v1[], const int v2[], int count);
extern inline int vector3i_dot(const int v1[3], const int v2[3]);
extern inline int vector4i_dot(const int v1[4], const int v2[4]);
extern inline void vector3i_cross_new(int result[3], const int v1[3], const int v2[3]);
extern inline int vector3i_normSq(const int v[3]);
extern inline int vector4i_normSq(const int v[4]);
extern inline int vector3i_norm(const int v[3]);
extern inline int vector4i_norm(const int v[3]);
extern inline void vectorNi_scaleDiv_new(int result[], const int v[], const int scale, int count);
extern inline void vectorNi_scaleMul_new(int result[], const int v[], const int scale, int count);
extern inline void vector3i_scaleDiv_new(int result[3], const int v[3], const int scale);
extern inline void vector4i_scaleDiv_new(int result[4], const int v[4], const int scale);
extern inline void vector3i_scaleMul_new(int result[3], const int v[3], const int scale);
extern inline void vector4i_scaleMul_new(int result[4], const int v[4], const int scale);
extern inline void vector3i_scaleDiv(int v[3], const int scale);
extern inline void vector3i_scaleMul(int v[3], const int scale);
extern inline void vector4i_scaleDiv(int v[3], const int scale);
extern inline void vector4i_scaleMul(int v[3], const int scale);
extern inline void vector3i_normalize_new(int result[3], const int v[3]);
extern inline void vector4i_normalize_new(int result[4], const int v[4]);
extern inline void vector3i_normalize(int v[3]);
extern inline void vector4i_normalize(int v[4]);
extern inline void vectorNi_add_new(int result[], const int v1[], const int v2[], const int count);
extern inline void vectorNi_sub_new(int result[], const int v1[], const int v2[], const int count);
extern inline void vector3i_add_new(int result[3], const int v1[3], const int v2[3]);
extern inline void vector3i_sub_new(int result[3], const int v1[3], const int v2[3]);
extern inline void vector4i_add_new(int result[4], const int v1[4], const int v2[4]);
extern inline void vector4i_sub_new(int result[4], const int v1[4], const int v2[4]);
extern inline void vector3i_add(int v1[3], const int v2[3]);
extern inline void vector3i_sub(int v1[3], const int v2[3]);
extern inline void vector4i_add(int v1[4], const int v2[4]);
extern inline void vector4i_sub(int v1[4], const int v2[4]);
extern inline void vector4i_homogenize_new(int result[4], const int v[4]);
extern inline void vector4i_homogenize(int v[3]);
extern inline void vectorNi_print(const int v[], int count);
extern inline void vector3i_print(const int v[3]);
extern inline void vector4i_print(const int v[4]);
extern inline void vector3i_reflect_new(int result[3], const int d[3], const int n[3]);
extern inline void vector4i_reflect_new(int result[4], const int d[4], const int n[4]);
extern inline void vector3f_set(float v[3], float a, float b, float c);
extern inline void vector4f_set(float v[3], float a, float b, float c, float w);
extern inline void vector3f_copy(float dest[3], const float src[3]);
extern inline void vector4f_copy(float dest[4], const float src[4]);
extern inline float vectorNf_dot(const float v1[], const float v2[], int count);
extern inline float vector3f_dot(const float v1[3], const float v2[3]);
extern inline float vector4f_dot(const float v1[4], const float v2[4]);
extern inline void vector3f_cross_new(float result[3], const float v1[3], const float v2[3]);
extern inline float vector3f_normSq(const float v[3]);
extern inline float vector4f_normSq(const float v[4]);
extern inline float vector3f_norm(const float v[3]);
extern inline float vector4f_norm(const float v[3]);
extern inline void vectorNf_scaleDiv_new(float result[], const float v[], const float scale, int count);
extern inline void vectorNf_scaleMul_new(float result[], const float v[], const float scale, int count);
extern inline void vector3f_scaleDiv_new(float result[3], const float v[3], const float scale);
extern inline void vector4f_scaleDiv_new(float result[4], const float v[4], const float scale);
extern inline void vector3f_scaleMul_new(float result[3], const float v[3], const float scale);
extern inline void vector4f_scaleMul_new(float result[4], const float v[4], const float scale);
extern inline void vector3f_scaleDiv(float v[3], const float scale);
extern inline void vector3f_scaleMul(float v[3], const float scale);
extern inline void vector4f_scaleDiv(float v[3], const float scale);
extern inline void vector4f_scaleMul(float v[3], const float scale);
extern inline void vector3f_normalize_new(float result[3], const float v[3]);
extern inline void vector4f_normalize_new(float result[4], const float v[4]);
extern inline void vector3f_normalize(float v[3]);
extern inline void vector4f_normalize(float v[4]);
extern inline void vectorNf_add_new(float result[], const float v1[], const float v2[], const int count);
extern inline void vectorNf_sub_new(float result[], const float v1[], const float v2[], const int count);
extern inline void vector3f_add_new(float result[3], const float v1[3], const float v2[3]);
extern inline void vector3f_sub_new(float result[3], const float v1[3], const float v2[3]);
extern inline void vector4f_add_new(float result[4], const float v1[4], const float v2[4]);
extern inline void vector4f_sub_new(float result[4], const float v1[4], const float v2[4]);
extern inline void vector3f_add(float v1[3], const float v2[3]);
extern inline void vector3f_sub(float v1[3], const float v2[3]);
extern inline void vector4f_add(float v1[4], const float v2[4]);
extern inline void vector4f_sub(float v1[4], const float v2[4]);
extern inline void vector4f_homogenize_new(float result[4], const float v[4]);
extern inline void vector4f_homogenize(float v[3]);
extern inline void vectorNf_print(const float v[], int count);
extern inline void vector3f_print(const float v[3]);
extern inline void vector4f_print(const float v[4]);
extern inline void vector3f_reflect_new(float result[3], const float d[3], const float n[3]);
extern inline void vector4f_reflect_new(float result[4], const float d[4], const float n[4]);
extern inline void vector3d_set(double v[3], double a, double b, double c);
extern inline void vector4d_set(double v[3], double a, double b, double c, double w);
extern inline void vector3d_copy(double dest[3], const double src[3]);
extern inline void vector4d_copy(double dest[4], const double src[4]);
extern inline double vectorNd_dot(const double v1[], const double v2[], int count);
extern inline double vector3d_dot(const double v1[3], const double v2[3]);
extern inline double vector4d_dot(const double v1[4], const double v2[4]);
extern inline void vector3d_cross_new(double result[3], const double v1[3], const double v2[3]);
extern inline double vector3d_normSq(const double v[3]);
extern inline double vector4d_normSq(const double v[4]);
extern inline double vector3d_norm(const double v[3]);
extern inline double vector4d_norm(const double v[3]);
extern inline void vectorNd_scaleDiv_new(double result[], const double v[], const double scale, int count);
extern inline void vectorNd_scaleMul_new(double result[], const double v[], const double scale, int count);
extern inline void vector3d_scaleDiv_new(double result[3], const double v[3], const double scale);
extern inline void vector4d_scaleDiv_new(double result[4], const double v[4], const double scale);
extern inline void vector3d_scaleMul_new(double result[3], const double v[3], const double scale);
extern inline void vector4d_scaleMul_new(double result[4], const double v[4], const double scale);
extern inline void vector3d_scaleDiv(double v[3], const double scale);
extern inline void vector3d_scaleMul(double v[3], const double scale);
extern inline void vector4d_scaleDiv(double v[3], const double scale);
extern inline void vector4d_scaleMul(double v[3], const double scale);
extern inline void vector3d_normalize_new(double result[3], const double v[3]);
extern inline void vector4d_normalize_new(double result[4], const double v[4]);
extern inline void vector3d_normalize(double v[3]);
extern inline void vector4d_normalize(double v[4]);
extern inline void vectorNd_add_new(double result[], const double v1[], const double v2[], const int count);
extern inline void vectorNd_sub_new(double result[], const double v1[], const double v2[], const int count);
extern inline void vector3d_add_new(double result[3], const double v1[3], const double v2[3]);
extern inline void vector3d_sub_new(double result[3], const double v1[3], const double v2[3]);
extern inline void vector4d_add_new(double result[4], const double v1[4], const double v2[4]);
extern inline void vector4d_sub_new(double result[4], const double v1[4], const double v2[4]);
extern inline void vector3d_add(double v1[3], const double v2[3]);
extern inline void vector3d_sub(double v1[3], const double v2[3]);
extern inline void vector4d_add(double v1[4], const double v2[4]);
extern inline void vector4d_sub(double v1[4], const double v2[4]);
extern inline void vector4d_homogenize_new(double result[4], const double v[4]);
extern inline void vector4d_homogenize(double v[3]);
extern inline void vectorNd_print(const double v[], int count);
extern inline void vector3d_print(const double v[3]);
extern inline void vector4d_print(const double v[4]);
extern inline void vector3d_reflect_new(double result[3], const double d[3], const double n[3]);
extern inline void vector4d_reflect_new(double result[4], const double d[4], const double n[4]);
